---
language: scala
scala:
        2.11.2
#script: "sbt coveralls"
notifications:
  email:
    recipients:
      - ivan.kuraj@gmail.com
    on_success: change
    on_failure: always
jdk:
- oraclejdk7
- openjdk7
# whitelist
branches:
  only:
    - master
    - develop
